spring:
  datasource:
    url: ## YOUR DATABASE URL
    username: ## YOUR DATABASE USERNAME
    password: ## YOUR DATABASE PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  mail:
    host: ## YOUR HOST
    port: ## YOUR PORT
    username: ## YOUR EMAIL USERNAME
    password: ## YOUR EMAIL PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: ## YOUR HOST
      port: ## YOUR PORT
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: ## YOUR KEY PREFIX
server:
  port: 8888

app:
  jwtSecret: ## YOUR JWT SECRET
  jwtExpirationInMs: 36000000

cloudinary:
  cloud_name: ## YOUR CLOUDINARY NAME
  api_key: ## YOUR CLOUDINARY API KEY
  api_secret: ## YOUR CLOUDINARY API SECRET


client-application:
  host: ## YOUR DOMAIN NAME
  route:
    password:
      reset: "/reset-password"
    user: "/user"
    article: "/article"
    announcement: "/announcement"
admin-panel:
  host: ## YOUR CLOUDINARY NAME + :7777
  route:
    article: "/articles"
    user: "/user"
